export const SWARM_VAULT_ABI = [
  {
    type: "event",
    name: "Deposit",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "newShares", type: "uint128" },
      { indexed: false, name: "totalUsers", type: "uint64" },
    ],
  },
  {
    type: "event",
    name: "Withdraw",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "sharesBurned", type: "uint128" },
    ],
  },
  {
    type: "event",
    name: "CopyToggled",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: false, name: "enabled", type: "bool" },
    ],
  },
  {
    type: "event",
    name: "UserSignal",
    inputs: [
      { indexed: true, name: "user", type: "address" },
      { indexed: true, name: "marketId", type: "bytes32" },
      { indexed: false, name: "marketSlug", type: "string" },
      { indexed: false, name: "lean", type: "int8" },
      { indexed: false, name: "note", type: "string" },
      { indexed: false, name: "timestamp", type: "uint64" },
    ],
  },
  {
    type: "event",
    name: "PositionOpened",
    inputs: [
      { indexed: true, name: "id", type: "uint256" },
      { indexed: true, name: "agent", type: "address" },
      { indexed: true, name: "marketId", type: "bytes32" },
      { indexed: false, name: "marketSlug", type: "string" },
      { indexed: false, name: "action", type: "uint8" },
      { indexed: false, name: "sizeUsdc", type: "uint64" },
      { indexed: false, name: "entryProbBps", type: "uint64" },
      { indexed: false, name: "rationale", type: "string" },
      { indexed: false, name: "polygonTxHash", type: "bytes32" },
      { indexed: false, name: "timestamp", type: "uint64" },
    ],
  },
  {
    type: "event",
    name: "PositionMarked",
    inputs: [
      { indexed: true, name: "id", type: "uint256" },
      { indexed: false, name: "unrealizedDeltaMicroUsdc", type: "int64" },
      { indexed: false, name: "markProbBps", type: "uint64" },
    ],
  },
  {
    type: "event",
    name: "PositionSettled",
    inputs: [
      { indexed: true, name: "id", type: "uint256" },
      { indexed: false, name: "pnlMicroUsdc", type: "int64" },
      { indexed: false, name: "polygonTxHash", type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setCopyEnabled",
    stateMutability: "nonpayable",
    inputs: [{ name: "enabled", type: "bool" }],
    outputs: [],
  },
  {
    type: "function",
    name: "sendSignal",
    stateMutability: "nonpayable",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "marketSlug", type: "string" },
      { name: "lean", type: "int8" },
      { name: "note", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "openPosition",
    stateMutability: "nonpayable",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "marketSlug", type: "string" },
      { name: "action", type: "uint8" },
      { name: "sizeUsdc", type: "uint64" },
      { name: "entryProbBps", type: "uint64" },
      { name: "rationale", type: "string" },
      { name: "polygonTxHash", type: "bytes32" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "markPosition",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "markProbBps", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "settlePosition",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "pnlMicroUsdc", type: "int64" },
      { name: "polygonTxHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "stats",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "totalDeposits", type: "uint256" },
      { name: "totalShares", type: "uint256" },
      { name: "userCount", type: "uint64" },
      { name: "signalCount", type: "uint64" },
      { name: "positionCount", type: "uint64" },
      { name: "realized", type: "int256" },
      { name: "unrealized", type: "int256" },
    ],
  },
  {
    type: "function",
    name: "userInfo",
    stateMutability: "view",
    inputs: [{ name: "u", type: "address" }],
    outputs: [
      { name: "deposited", type: "uint128" },
      { name: "withdrawn", type: "uint128" },
      { name: "shares", type: "uint128" },
      { name: "copyEnabled", type: "bool" },
      { name: "estimatedPnlMicroUsdc", type: "int256" },
    ],
  },
] as const;
